- name: Create credentials 
  hosts: localhost
  gather_facts: no
  vars:
    organization_name: "{{ organization_name }}"
    credential_name: "{{ credential_name }}"
    credential_type: "{{ credential_type }}"
    credential_inputs:
      username: "{{ cred_username }}"
      password: "{{ cred_password }}"
    my_auth_token: "E1XuylA0mX74Pwoe6ntUvGPyf6bzGz"
    base_api_url: "http://192.168.56.105:10445/api/v2"
  tasks:
    - name: Create credential
      uri:
        url: "{{base_api_url}}/credentials/"
        method: Get 
        headers:
          Authorization: "Bearer {{ my_auth_token }}"
      register: create_credential_response

    - name: Debug create credential response 
      debug:
        var: create_credential_response 

