
---
- name: Get Organization ID
  hosts: localhost
  gather_facts: false
  vars:
    organization_name: "{{ organization_name }}"  # Use the survey variable
    scm_credential_name: "{{ scm_credential_name }}"

  tasks:
    - name: Call the API to get organization details
      uri:
        url: "http://192.168.56.105:10445/api/v2/organizations/"
        method: GET
        headers:
          Authorization: "Bearer E1XuylA0mX74Pwoe6ntUvGPyf6bzGz"
      register: api_response

    - name: Extract organization ID
      set_fact:
        organization_id: "{{ item.id }}"
      with_items: "{{ api_response.json.results }}"
      when: item.name == organization_name

    - name: Display organization ID
      debug:
        var: organization_id

    - name: Call the API to get SCM credentials details
      uri:
        url: "http://192.168.56.105:10445/api/v2/credentials/"
        method: GET
        headers:
          Authorization: "Bearer E1XuylA0mX74Pwoe6ntUvGPyf6bzGz"
      register: api_response2

    - name: Extract SCM Credential ID
      set_fact:
        scm_credential_id: "{{ item.id }}"
      with_items: "{{ api_response2.json.results }}"
      when: item.name == scm_credential_name

    - name: Display SCM Credential ID
      debug:
        var: scm_credential_id
