---
- name: Get AWX Project
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve Project Details
      uri:
        url: http://192.168.56.105:10445/api/v2/projects/
        method: GET
        headers:
          Authorization: "Bearer E1XuylA0mX74Pwoe6ntUvGPyf6bzGz"
      register: project_result

    - name: Display Project Info
      debug:
        var: project_result.json.results
