- name: Create AAP Project
  hosts: localhost
  gather_facts: no
  vars:
    organization_name: "{{ organization_name }}"  
    scm_credential_name: "{{ scm_credential_name }}"
    my_auth_token: "E1XuylA0mX74Pwoe6ntUvGPyf6bzGz"
    base_api_url: "http://192.168.56.105:10445/api/v2"

  tasks:
    - name: Call the API to get organization details
      uri:
        url: "{{ base_api_url }}/organizations/"
        method: GET
        headers:
          Authorization: "Bearer {{ my_auth_token }}"
      register: api_response

    - name: Extract organization ID
      set_fact:
        organization_id: "{{ item.id }}"
      with_items: "{{ api_response.json.results }}"
      when: item.name == organization_name

    - name: Fail if organization name not available
      fail:
        msg: "Organization name {{ organization_name }} not found"
      when: organization_id is not defined

    - name: Call the API to get SCM credentials details
      uri:
        url: "{{ base_api_url }}/credentials/"
        method: GET
        headers:
          Authorization: "Bearer {{ my_auth_token }}"
      register: api_response

    - name: Extract SCM Credential ID
      set_fact:
        scm_credential_id: "{{ item.id }}"
      with_items: "{{ api_response.json.results }}"
      when: item.name == scm_credential_name

   - name: Fail if SCM Credential name not available
     fail:
       msg: "SCM Credential {{ scm_credential_name }} not found."
     when: scm_credential_id is not defined

    - name: Create AAP Project
      uri:
        url: "{{ base_api_url }}/projects/"
        method: POST
        headers:
          Authorization: "Bearer {{ my_auth_token }}"
        body_format: json
        body:
          name: "{{ project_name }}"
          description: "{{ project_description }}"
          scm_type: git
          scm_url: "{{ scm_repo_url }}"
          scm_branch: "{{ scm_branch }}"
          scm_clean: true
          credential: "{{ scm_credential_id }}"
          scm_update_on_launch: true
          organization: "{{ organization_id }}"
      register: project_result
      ignore_errors: true

    - name: Display project creation result
      debug:
        var: project_result.json
